### ISSUE TITLE
close function not documented

### ISSUE THREAD

**Issue by andischmid** [MarioRuiz/nice_http#11]
The function to close a connection is not documented in the readme but implemented in the code.
I ran into problems ("too many files open") when I opened HTTP connections in a frequently triggered callback function but did not close them rpoperly.

**Comment by MarioRuiz** [comment]
To close the connection all you have to do is: `http.close` and there are no parameters. Not everything is documented on the readme for full documentation take a look at https://www.rubydoc.info/gems/nice_http/NiceHttp 
Probably the issue you are facing is not related directly to not closing the connections but creating the log files but closing the connections when not needed would solve it. 
If you close the connections are you still having the issue?

**Comment by MarioRuiz** [comment]
Also if you don't want the http logs to be generated you can set for all http connections: `NiceHttp.logs = :no`
Or you can specify it for specific connections: `http = NiceHttp.new(host: 'http://www.example.com', log: :no)`
